services:
    ezplatform.http_cache.store:
        alias: ezplatform.http_cache.tag_aware_store

    ezplatform.http_cache.tag_aware_store:
        class: EzSystems\PlatformHttpCacheBundle\Proxy\TagAwareStore
        arguments: ["%ezplatform.http_cache.store.root%"]
