services:
    ezplatform.view_cache.response_subscriber:
        class: EzSystems\PlatformHttpCacheBundle\EventSubscriber\HttpCacheResponseSubscriber
        arguments:
            - '@ezplatform.view_cache.response_configurator'
            - '@ezplatform.view_cache.view_tagger.dispatcher'
            - '@ezplatform.http_cache.tag_handler'
        tags:
            - { name: kernel.event_subscriber }

    ezplatform.x_location_id.response_subscriber:
        class: EzSystems\PlatformHttpCacheBundle\EventSubscriber\XLocationIdResponseSubscriber
        arguments: ['@ezplatform.http_cache.tag_handler', '@ezpublish.api.repository']
        tags:
            - { name: kernel.event_subscriber }

    ezplatform.view_cache.response_configurator:
        class: EzSystems\PlatformHttpCacheBundle\ResponseConfigurator\ConfigurableResponseCacheConfigurator
        arguments:
            - '$content.view_cache$'
            - '$content.ttl_cache$'
            - '$content.default_ttl$'

    ezplatform.view_cache.view_tagger.dispatcher:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\View\DispatcherTagger
        # Taggers are added by a compiler pass
        arguments:
            - []

    ezplatform.view_cache.view_tagger.content_value_view:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\View\ContentValueViewTagger
        arguments: ['@ezplatform.view_cache.value_tagger.content_info']
        tags:
            - {name: ezplatform.view_cache.view_tagger}

    ezplatform.view_cache.view_tagger.location_value_view:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\View\LocationValueViewTagger
        arguments: ['@ezplatform.view_cache.value_tagger.location']
        tags:
            - {name: ezplatform.view_cache.view_tagger}

    ezplatform.view_cache.value_tagger.dispatcher:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\Value\DispatcherTagger
        # Taggers are added by a compiler pass
        arguments:
            - []

    ezplatform.view_cache.value_tagger.content_info:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\Value\ContentInfoTagger
        tags:
            - {name: ezplatform.view_cache.value_tagger}

    ezplatform.view_cache.value_tagger.location:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\Value\LocationTagger
        tags:
            - {name: ezplatform.view_cache.value_tagger}
